### YamlMime:ManagedReference
items:
- uid: EasySave.Data.Configuration
  commentId: N:EasySave.Data.Configuration
  id: EasySave.Data.Configuration
  children:
  - EasySave.Data.Configuration.ApplicationConfiguration
  - EasySave.Data.Configuration.DataPathResolver
  langs:
  - csharp
  - vb
  name: EasySave.Data.Configuration
  nameWithType: EasySave.Data.Configuration
  fullName: EasySave.Data.Configuration
  type: Namespace
  assemblies:
  - EasySave
references:
- uid: EasySave.Data.Configuration.ApplicationConfiguration
  commentId: T:EasySave.Data.Configuration.ApplicationConfiguration
  parent: EasySave.Data.Configuration
  href: EasySave.Data.Configuration.ApplicationConfiguration.html
  name: ApplicationConfiguration
  nameWithType: ApplicationConfiguration
  fullName: EasySave.Data.Configuration.ApplicationConfiguration
- uid: EasySave.Data.Configuration.DataPathResolver
  commentId: T:EasySave.Data.Configuration.DataPathResolver
  href: EasySave.Data.Configuration.DataPathResolver.html
  name: DataPathResolver
  nameWithType: DataPathResolver
  fullName: EasySave.Data.Configuration.DataPathResolver
- uid: EasySave.Data.Configuration
  commentId: N:EasySave.Data.Configuration
  href: EasySave.html
  name: EasySave.Data.Configuration
  nameWithType: EasySave.Data.Configuration
  fullName: EasySave.Data.Configuration
  spec.csharp:
  - uid: EasySave
    name: EasySave
    href: EasySave.html
  - name: .
  - uid: EasySave.Data
    name: Data
    href: EasySave.Data.html
  - name: .
  - uid: EasySave.Data.Configuration
    name: Configuration
    href: EasySave.Data.Configuration.html
  spec.vb:
  - uid: EasySave
    name: EasySave
    href: EasySave.html
  - name: .
  - uid: EasySave.Data
    name: Data
    href: EasySave.Data.html
  - name: .
  - uid: EasySave.Data.Configuration
    name: Configuration
    href: EasySave.Data.Configuration.html
